version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: cc-mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: community-connect

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: cc-backend
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/community-connect
      - PORT=3000
      - NODE_ENV=production
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: cc-frontend
    ports:
      - '4200:4200'
    depends_on:
      - backend

volumes:
  mongodb_data:
